version: "3.9"
services:
  pdfity:
    image: nehcy/pdfity
    container_name: PGFity 
    build: . 
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    volumes:
      - ./work:/home/wald/work
      - ./tmp:/tmp/gradio
    command: gradio app.py
    init: true
    restart: always
    stdin_open: true    
    network_mode: bridge
    tty: true
    ports:
      - 7863:7860
